import type { Planet } from '@/types';

export const PLANETS: Planet[] = [
  {
    id: '1',
    slug: 'html',
    name: 'HTML',
    planetName: 'Terra Digital',
    description: 'A fundação de toda a web. Construa a estrutura de mundos digitais.',
    language: 'HTML',
    icon: '🌐',
    color: '#00D4FF',
    progress: 100,
    totalLessons: 20,
    completedLessons: 20,
    requiredLevel: 1,
  },
  {
    id: '2',
    slug: 'css',
    name: 'CSS',
    planetName: 'Neon City',
    description: 'Estilize realidades. Domine layouts, animações e design futurista.',
    language: 'CSS',
    icon: '🎨',
    color: '#8B5CF6',
    progress: 65,
    totalLessons: 25,
    completedLessons: 16,
    requiredLevel: 1,
  },
  {
    id: '3',
    slug: 'javascript',
    name: 'JavaScript',
    planetName: 'Cyber Core',
    description: 'O coração pulsante da web. Dê vida às máquinas.',
    language: 'JavaScript',
    icon: '⚡',
    color: '#FFD700',
    progress: 30,
    totalLessons: 30,
    completedLessons: 9,
    requiredLevel: 1,
  },
  {
    id: '4',
    slug: 'typescript',
    name: 'TypeScript',
    planetName: 'Quantum Station',
    description: 'Código com superpoderes. Tipagem que transcende dimensões.',
    language: 'TypeScript',
    icon: '🔷',
    color: '#3178C6',
    progress: 0,
    totalLessons: 28,
    completedLessons: 0,
    requiredLevel: 5,
  },
  {
    id: '5',
    slug: 'react',
    name: 'React',
    planetName: 'React Nexus',
    description: 'Interfaces que reagem. Componentes de pura energia.',
    language: 'React',
    icon: '⚛️',
    color: '#61DAFB',
    progress: 0,
    totalLessons: 32,
    completedLessons: 0,
    requiredLevel: 8,
  },
  {
    id: '6',
    slug: 'nodejs',
    name: 'Node.js',
    planetName: 'Backend Colony',
    description: 'Servidores em colônias autônomas. APIs que nunca dormem.',
    language: 'Node.js',
    icon: '🟢',
    color: '#339933',
    progress: 0,
    totalLessons: 30,
    completedLessons: 0,
    requiredLevel: 10,
  },
  {
    id: '7',
    slug: 'python',
    name: 'Python',
    planetName: 'AI Planet',
    description: 'O planeta orgânico onde máquinas aprendem a pensar.',
    language: 'Python',
    icon: '🐍',
    color: '#00FF88',
    progress: 0,
    totalLessons: 35,
    completedLessons: 0,
    requiredLevel: 12,
  },
  {
    id: '8',
    slug: 'java',
    name: 'Java',
    planetName: 'Enterprise World',
    description: 'Fortalezas corporativas. Sistemas que sustentam civilizações.',
    language: 'Java',
    icon: '☕',
    color: '#F89820',
    progress: 0,
    totalLessons: 30,
    completedLessons: 0,
    requiredLevel: 15,
  },
  {
    id: '9',
    slug: 'sql',
    name: 'SQL',
    planetName: 'Data Matrix',
    description: 'A matrix dos dados. Consultas que desvendam realidades.',
    language: 'SQL',
    icon: '🗄️',
    color: '#E48E00',
    progress: 0,
    totalLessons: 22,
    completedLessons: 0,
    requiredLevel: 5,
  },
  {
    id: '10',
    slug: 'git',
    name: 'Git',
    planetName: 'Version Control Base',
    description: 'A base do tempo. Controle suas linhas temporais.',
    language: 'Git',
    icon: '🔀',
    color: '#F05032',
    progress: 0,
    totalLessons: 18,
    completedLessons: 0,
    requiredLevel: 1,
  },
];
